apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-parkplatz
  name: ms-parkplatz
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-parkplatz
    spec:
      containers:
        - image: ms-parkplatz-frontend
          name: ms-parkplatz-frontend
          ports:
            - containerPort: 80
        - image: ms-parkplatz-backend
          name: ms-parkplatz-backend
          ports:
            - containerPort: 8080
            - containerPort: 50051
        - image: ms-parkplatz-database
          name: ms-parkplatz-database
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "test"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASES
              value: "parkspace"
        - image: ms-parkplatz-cache
          name: ms-parkplatz-cache
          ports:
            - containerPort: 6379
      restartPolicy: Always
status: {}
