name: ParkSpace frontend CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci
        working-directory: ./frontend/ParkSpace

      - name: Build production bundle
        run: ./node_modules/.bin/ng build --prod
        working-directory: ./frontend/ParkSpace

      - name: Lint
        run: ./node_modules/.bin/ng lint
        working-directory: ./frontend/ParkSpace

      - name: Test
        run: ./node_modules/.bin/ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./frontend/ParkSpace
